Repository hochschule-darmstadt/openartbrowser, pull requests merged in 2019-12, with the labels that each got.

#78 Multilanguage backend to staging
  .gitignore
  scripts/Wikidata crawler/ArtOntologyCrawler.py
  scripts/Wikidata crawler/language_helper.py
  scripts/Wikidata crawler/languageconfig.csv
  scripts/Wikidata crawler/requirements.txt
  scripts/Wikidata crawler/split_languages.py
Labels: feature

#97 Enhancement/90/mobile support
  app/src/app/core/components/header/header.component.html
  app/src/app/core/components/header/header.component.scss
  app/src/app/pages/artwork/artwork.component.scss
  app/src/app/shared/components/slider/slider.component.ts
Labels: enhancement

#127 Bug/54
  app/package-lock.json
  app/package.json
Labels: bug

#128 Feature/95 only image requried
  scripts/Wikidata crawler/ArtOntologyCrawler.py
Labels: enhancement

#126 Upgrade to Angular 8
  .travis.yml
  app/package-lock.json
  app/package.json
  app/src/app/pages/home/home.routing.module.ts
Labels: dependencies

#162 Bug/85/unexpected search order
  app/src/app/shared/components/search/search.component.ts
Labels: bug

#166 bug/146/material_page
  app/src/app/pages/material/material.component.html
Labels: bug

#137 Fix/107/backend tests
  .travis.yml
  scripts/Wikidata crawler/ArtOntologyCrawler.py
Labels: bug, enhancement

#173 Enhancement/119 switch es indices
  scripts/run_etl.bat
  scripts/upload_to_elasticsearch/elasticsearch_helper.py
  scripts/upload_to_elasticsearch/server_elasticsearch.yml
Labels: elasticsearch, enhancement

#171 artwork component refactoring
  app/src/app/pages/artist/artist.component.html
  app/src/app/pages/artwork/artwork.component.html
  app/src/app/pages/artwork/artwork.component.ts
  app/src/app/pages/genre/genre.component.html
  app/src/app/pages/home/home.component.html
  app/src/app/pages/location/location.component.html
  app/src/app/pages/material/material.component.html
  app/src/app/pages/motif/motif.component.html
  app/src/app/pages/movement/movement.component.html
  app/src/app/shared/components/search/search.component.html
  app/src/app/shared/models/entityicon.enum.ts
  app/src/app/shared/models/entitytype.enum.ts
  app/src/locale/messages.de.xlf
  app/src/locale/messages.en.xlf
  app/src/locale/messages.es.xlf
  app/src/locale/messages.fr.xlf
  app/src/locale/messages.it.xlf
  app/src/locale/messages.xlf
Labels: enhancement

#170 Bug/150/ui bugs
  app/angular.json
  app/package-lock.json
  app/src/app/pages/artist/artist.component.html
  app/src/app/pages/artwork/artwork.component.html
  app/src/app/pages/artwork/artwork.component.scss
  app/src/app/pages/artwork/artwork.component.ts
  app/src/app/pages/home/home.component.html
  app/src/app/pages/home/home.component.scss
  app/src/app/shared/components/carousel/carousel.component.scss
  app/src/app/shared/shared.module.ts
  app/src/styles.scss
  app/src/styles/entity.scss
  app/src/styles/main.scss
  app/src/styles/styles.scss
Labels: bug, enhancement

#187 Bug/184/timeline artworks toggle not clickable
  .github/ISSUE_TEMPLATE/bug_report.md
  app/src/app/pages/artist/artist.component.html
  app/src/app/pages/artist/artist.component.spec.ts
  app/src/app/pages/artist/artist.component.ts
  app/src/app/pages/artwork/artwork.component.html
  app/src/app/pages/artwork/artwork.component.spec.ts
  app/src/app/pages/artwork/artwork.component.ts
  app/src/app/pages/genre/genre.component.html
  app/src/app/pages/genre/genre.component.spec.ts
  app/src/app/pages/location/location.component.html
  app/src/app/pages/location/location.component.spec.ts
  app/src/app/pages/location/location.component.ts
  app/src/app/pages/material/material.component.html
  app/src/app/pages/motif/motif.component.html
  app/src/app/pages/movement/movement.component.html
  app/src/app/pages/movement/movement.component.spec.ts
  app/src/app/pages/movement/movement.component.ts
  app/src/app/shared/components/collapse/collapse.component.html
  app/src/app/shared/components/collapse/collapse.component.scss
  app/src/app/shared/components/collapse/collapse.component.spec.ts
  app/src/app/shared/components/collapse/collapse.component.ts
  app/src/app/shared/components/video/video.component.ts
  app/src/app/shared/shared.module.ts
  app/src/styles/entity.scss
Labels: bug

#213 Fix/elasticsearch index swap
  scripts/upload_to_elasticsearch/elasticsearch_helper.py
Labels: elasticsearch
