Repository hochschule-darmstadt/openartbrowser, pull requests merged in 2020-06, with the labels that each got.

#379 fix : in iconclass label
  app/src/app/pages/artwork/artwork.component.html
  app/src/app/shared/components/iconclass/iconclass.component.html
  app/src/app/shared/components/iconclass/iconclass.component.ts
Labels: bug

#390 Feature/rdf with new attributes
  etl/data_extraction/get_wikidata_items.py
  etl/data_extraction/map_wd_attribute.py
  etl/generate_rdf/art_ontology_header.txt
  etl/generate_rdf/generate_rdf.py
Labels: feature

#415 #412: removed default cursor style from heading pill
  app/src/app/shared/components/title/title.component.html
  app/src/styles/entity.scss
Labels: bug

#416 Changes to entities component #414
  app/src/app/pages/entities/entities.component.html
  app/src/app/pages/entities/entities.component.ts
Labels: refactoring

#397 Issue 410 [exhibition history]
  app/src/app/pages/artwork/artwork.component.html
  app/src/app/pages/artwork/artwork.component.spec.ts
  app/src/app/pages/artwork/artwork.component.ts
  app/src/app/shared/components/event-table/event-table.component.css
  app/src/app/shared/components/event-table/event-table.component.css.map
  app/src/app/shared/components/event-table/event-table.component.html
  app/src/app/shared/components/event-table/event-table.component.scss
  app/src/app/shared/components/event-table/event-table.component.spec.ts
  app/src/app/shared/components/event-table/event-table.component.ts
  app/src/app/shared/models/artwork.interface.ts
  app/src/app/shared/shared.module.ts
  app/src/locale/messages.de.xlf
  app/src/locale/messages.en.xlf
  app/src/locale/messages.es.xlf
  app/src/locale/messages.fr.xlf
  app/src/locale/messages.it.xlf
Labels: feature
