Repository hochschule-darmstadt/openartbrowser, pull requests merged in 2021-06, with the labels that each got.

#503 476/movement timeline alignment
  app/src/app/pages/movement/movement.component.html
  app/src/app/shared/components/movement-overview/movement-overview.component.ts
Labels: User Interface, bug

#508 452/Add_additional_types_to_crawling_process and 502/GitHub actions deployment
  .github/workflows/deployment-production.yml
  .github/workflows/deployment-staging.yml
  .github/workflows/tests.yml
  app/.gitignore
  app/package-lock.json
  app/package.json
  etl/Dockerfile
  etl/data_enhancement/add_youtube_videos.py
  etl/data_enhancement/estimate_movement_period.py
  etl/data_enhancement/has_part_part_of_enhancement.py
  etl/data_enhancement/ranking.py
  etl/data_enhancement/split_languages.py
  etl/data_extraction/constants.py
  etl/data_extraction/get_wikidata_items.py
  etl/data_extraction/get_wikipedia_extracts.py
  etl/data_extraction/load_wd_entities.py
  etl/requirements.txt
  etl/scripts/etl.sh
  etl/scripts/run_etl.sh
  etl/shared/constants.py
  etl/shared/utils.py
Labels: etl process, high priority

#511 493/new type class in UI
  app/src/app/app.routing.module.ts
  app/src/app/pages/artist/artist.component.html
  app/src/app/pages/artwork/artwork.component.html
  app/src/app/pages/artwork/artwork.component.ts
  app/src/app/pages/class/class.component.html
  app/src/app/pages/class/class.component.scss
  app/src/app/pages/class/class.component.spec.ts
  app/src/app/pages/class/class.component.ts
  app/src/app/pages/class/class.routing.module.ts
  app/src/app/pages/entities/entities.component.html
  app/src/app/pages/entities/entities.component.ts
  app/src/app/pages/home/home.component.html
  app/src/app/pages/home/home.component.ts
  app/src/app/pages/location/location.component.html
  app/src/app/pages/motif/motif.component.html
  app/src/app/pages/movement/movement.component.html
  app/src/app/shared/components/badge/badge.component.ts
  app/src/app/shared/components/category-container/category-container.component.html
  app/src/app/shared/components/category-container/category-container.component.ts
  app/src/app/shared/components/information/information.component.html
  app/src/app/shared/components/information/information.component.ts
  app/src/app/shared/components/search/search.component.html
  app/src/app/shared/components/search/search.component.ts
  app/src/app/shared/components/sticky-title/sticky-title.component.html
  app/src/app/shared/components/sticky-title/sticky-title.component.ts
  app/src/app/shared/components/title/title.component.html
  app/src/app/shared/components/title/title.component.ts
  app/src/app/shared/models/class.interface.ts
  app/src/app/shared/models/entity.interface.ts
  app/src/app/shared/models/models.ts
  app/src/locale/messages.de.xlf
  app/src/locale/messages.en.xlf
  app/src/locale/messages.es.xlf
  app/src/locale/messages.fr.xlf
  app/src/locale/messages.it.xlf
Labels: User Interface, medium priority

#526 #525: handle case if no thumbnail exists
  app/src/app/core/services/elasticsearch/data.service.ts
Labels: bug, medium priority

#534 #531: Align dimension label correctly
  app/src/app/shared/components/dimensions/dimensions.component.html
Labels: User Interface, small effort, usability improvement

#536 497/make related movement timeline mobile friendly
  app/src/app/shared/components/movement-overview/movement-overview.component.html
  app/src/app/shared/components/movement-overview/movement-overview.component.scss
  app/src/app/shared/components/movement-overview/movement-overview.component.ts
Labels: User Interface, medium priority, usability improvement

#535 #495: mobile overhaul - footer, header + other small adjustments
  app/src/app/core/components/footer/footer.component.html
  app/src/app/core/components/header/header.component.scss
  app/src/app/pages/home/home.component.scss
  app/src/assets/images/Wikidata_Stamp_Rec_Dark_compressed.svg
Labels: User Interface, medium priority

#530 Mobile Overhaul: Text Styling
  app/src/app/pages/data-protection/data-protection.component.html
  app/src/app/pages/data-protection/data-protection.component.scss
  app/src/app/shared/components/category-container/category-container.component.scss
  app/src/app/shared/components/sticky-title/sticky-title.component.html
  app/src/app/shared/components/sticky-title/sticky-title.component.scss
  app/src/styles/styles.scss
Labels: User Interface, usability improvement

#538 Mobile Overhaul: Paddings / Fetching List Width
  app/src/app/core/components/footer/footer.component.html
  app/src/app/core/components/footer/footer.component.scss
  app/src/app/pages/artist/artist.component.html
  app/src/app/pages/artist/artist.component.scss
  app/src/app/pages/artwork/artwork.component.html
  app/src/app/pages/artwork/artwork.component.scss
  app/src/app/pages/class/class.component.html
  app/src/app/pages/genre/genre.component.html
  app/src/app/pages/home/home.component.html
  app/src/app/pages/location/location.component.html
  app/src/app/pages/material/material.component.html
  app/src/app/pages/motif/motif.component.html
  app/src/app/pages/movement/movement.component.html
  app/src/app/pages/movement/movement.component.scss
  app/src/app/pages/search-result/search-result.component.html
  app/src/app/pages/search-result/search-result.component.scss
  app/src/app/shared/components/abstract/abstract.component.html
  app/src/app/shared/components/collapse/collapse.component.html
  app/src/app/shared/components/fetching-list/fetching-list.component.html
  app/src/app/shared/components/fetching-list/fetching-list.component.scss
  app/src/app/shared/components/sticky-title/sticky-title.component.html
  app/src/app/shared/components/timeline/timeline.component.html
  app/src/styles/styles.scss
Labels: User Interface, usability improvement

#528 500/tab layout
  app/src/app/pages/artist/artist.component.html
  app/src/app/pages/artist/artist.component.scss
  app/src/app/pages/artist/artist.component.ts
  app/src/app/pages/artwork/artwork.component.html
  app/src/app/pages/artwork/artwork.component.scss
  app/src/app/pages/artwork/artwork.component.ts
  app/src/app/pages/movement/movement.component.html
  app/src/app/pages/movement/movement.component.scss
  app/src/app/pages/movement/movement.component.ts
Labels: User Interface, feature, usability improvement

#544 496/update artwork page
  app/src/app/core/components/footer/footer.component.scss
  app/src/app/core/components/header/header.component.scss
  app/src/app/pages/artwork/artwork.component.html
  app/src/app/pages/artwork/artwork.component.scss
  app/src/app/pages/home/home.component.scss
  app/src/app/pages/search-result/search-result.component.scss
  app/src/app/shared/components/carousel/carousel.component.html
  app/src/app/shared/components/carousel/carousel.component.scss
  app/src/app/shared/components/carousel/carousel.component.ts
  app/src/app/shared/components/carousel/slide/slide.component.html
  app/src/app/shared/components/carousel/slide/slide.component.scss
  app/src/app/shared/components/carousel/slide/slide.component.ts
  app/src/app/shared/components/search/search.component.scss
  app/src/app/shared/models/artwork.interface.ts
  app/src/styles/styles.scss
Labels: User Interface, medium priority

#542 541/fix unrelated artworks in related artworks 'all' tab
  app/src/app/pages/artwork/artwork.component.ts
Labels: User Interface, bug
