Repository hochschule-darmstadt/openartbrowser, pull requests merged in 2021-04, with the labels that each got.

#478 Fix deployment build output
  app/angular.json
Labels: bug, staging server

#483 Various frontend fixes
  app/src/app/pages/movement/movement.component.ts
  app/src/app/shared/components/movement-overview/movement-overview.component.ts
Labels: User Interface, bug

#484 477/add error pages and messages
  app/src/app/app.routing.module.ts
  app/src/app/pages/artist/artist.component.html
  app/src/app/pages/artist/artist.component.ts
  app/src/app/pages/artwork/artwork.component.html
  app/src/app/pages/artwork/artwork.component.ts
  app/src/app/pages/error/error.component.html
  app/src/app/pages/error/error.component.scss
  app/src/app/pages/error/error.component.spec.ts
  app/src/app/pages/error/error.component.ts
  app/src/app/pages/error/error.routing.module.ts
  app/src/app/pages/genre/genre.component.html
  app/src/app/pages/genre/genre.component.ts
  app/src/app/pages/location/location.component.html
  app/src/app/pages/location/location.component.ts
  app/src/app/pages/material/material.component.html
  app/src/app/pages/material/material.component.ts
  app/src/app/pages/motif/motif.component.html
  app/src/app/pages/motif/motif.component.ts
  app/src/app/pages/movement/movement.component.html
  app/src/app/pages/movement/movement.component.ts
  app/src/app/shared/components/error-message/error-message.component.html
  app/src/app/shared/components/error-message/error-message.component.scss
  app/src/app/shared/components/error-message/error-message.component.spec.ts
  app/src/app/shared/components/error-message/error-message.component.ts
  app/src/app/shared/shared.module.ts
  app/src/locale/messages.de.xlf
  app/src/locale/messages.en.xlf
  app/src/locale/messages.es.xlf
  app/src/locale/messages.fr.xlf
  app/src/locale/messages.it.xlf
Labels: User Interface, feature, medium priority
